### PR TITLE
improve dictionary types, fix bugs, other small improvements

### PR DESCRIPTION
**Pull request by stevengj**
This patch uses `UInt8` for storing the ASCII character codes instead of `Char` (which is 4 bytes), and explicitly declares the types of all of the dictionaries.

In doing so, I caught several bugs where the dictionary keys had the wrong number of characters.   Most were obvious: somehow you had inserted extra spaces into the keys in some places (as was clear if I compared to tinysegmenter implementations in other languages, e.g. you had `", "` instead of `','` in `UW1`), and in some case you had the string `"B1"` instead of the constant `B1` etc.  But in one particular case (in `UW3`, _see below_) you had two codepoints where one was expected, and I guessed that the first codepoint was the one you wanted.  Please check.

### CODE REVIEW

**Comment by stevengj** [comment]
In particular, in `UW3` you were mapping `"ｸﾞ"` to 1319, but that dictionary expects only a single codepoint.  I guessed you wanted `'ｸ'`, but I'm not sure.

In particular, the second code point of `"ｸﾞ"` is [U+FF9E](http://www.fileformat.info/info/unicode/char/ff9e/index.htm), which is a "letter modifier".   So maybe you did mean the whole string `"ｸﾞ"`?  But in that case it looks like it should be in `BW2`, not `UW3`, in order to compare to two consecutive codepoints `(w3, w4)` rather than one `(w3)`.

I looked at some other tinysegmenter implementations, and the ones I looked at had a similar error.

**Comment by stevengj** [comment]
It would be good to have a more stringent test case that would catch these kinds of bugs, but since I don't know anything about Japanese I can't be much help there.

**Comment by stevengj** [comment]
I also pushed a few minor optimizations and other small improvements.

**Comment by chezou** [comment]
> you had `", "` instead of `','`

You are right. It's my mistake.

But `"ｸﾞ"` (sounds 'gu') does not mean `'ｸ'` (sounds 'ku'). It's completely different character. In full-width Katakana, we can handle as one character `'グ'` (sounds 'gu'), but half-width Katakana needs two character for `'グ'` in Unicode.

**Comment by stevengj** [comment]
So the `"ｸﾞ"` should be in the `BW2` table rather than `UW3`?

**Comment by stevengj** [comment]
I've pushed a commit to put `"ｸﾞ" => 1319` into `BW2` instead of `UW3`.

**Comment by chezou** [comment]
> So the "ｸﾞ" should be in the BW2 table rather than UW3?

Exactly. I tried following code and I found "ｸﾞ" becomes two characters, so `BW2` is correct.

```
julia> for c in "ｸﾞｰｸﾞﾙ"
           println(c)
       end
ｸ
ﾞ
ｰ
ｸ
ﾞ
ﾙ
```

**Comment by chezou** [comment]
I tried following code, `"ｸﾞ"` became two characters. So `BW2` is suitable than `UW3`

```
julia> for c in "ｸﾞｰｸﾞﾙ"
           println(c)
       end
ｸ
ﾞ
ｰ
ｸ
ﾞ
ﾙ
```

**Comment by stevengj** [comment]
Yes, it is important to understand the different notions of "character".   `"ｸﾞ"` is encoded as two codepoints (= 2 `Char`) in Unicode, and codepoints are one possible meaning of "character" — this is what a Julia `Char` is, and it has the advantage that `Char` has a fixed width (32 bits).

On the other hand, `"ｸﾞ"` is a single "grapheme" (roughly, what a native speaker thinks of as a "character") in Unicode.  You can see this with the `graphemes` function in Julia:

```
julia> collect(graphemes("ｸﾞｰｸﾞﾙ"))
4-element Array{SubString{UTF8String},1}:
 "ｸﾞ"
 "ｰ" 
 "ｸﾞ"
 "ﾙ" 
```

The disadvantage of graphemes is that they are not fixed width; you might need any number of bits to represent them, which is why the `graphemes` function returns an iterator over substrings.

But since your dictionaries operate on `Char` (on codepoints), you need to put it in `BW2`.

Note that this is **not specific to Julia**; it is a property of how Unicode represents `"ｸﾞ"`.  In _any language_ where the elements of a string are codepoints (which is most languages), putting `"ｸﾞ"` into `UW3` is a bug.

**Comment by chezou** [comment]
Original code of [tinysegmenter.js](http://chasen.org/~taku/software/TinySegmenter/tiny_segmenter-0.2.js) includes "ｸﾞ" in `UW3`, so most people didn't care about that, I think.

**Comment by stevengj** [comment]
It is a bug in the original code, then, because JavaScript strings iterate over codepoints.  (Or worse: [some versions of Javascript](https://mathiasbynens.be/notes/javascript-unicode) only iterate over codepoints in the BMP and expose UTF-16 surrogate pairs for other codepoints.  Yuck.)

The point is, if you put it in `UW3`, it will never get matched, because you are passing a single codepoint `w3` to `UW3`, and a single codepoint will never match the key `"ｸﾞ"`.

**Comment by stevengj** [comment]
It's probably a good idea to report the `"ｸﾞ"` bug to the original author; it's good etiquette to pass bug fixes [upstream](https://en.wikipedia.org/wiki/Upstream_%28software_development%29) like that.

**Comment by chezou** [comment]
I reported the issue to taku910 on twitter. https://twitter.com/chezou/status/654647110839595009

**Comment by chezou** [comment]
@stevengj 
Finally, taku910 realize the bug of model, but it was too late to remember how to create the first model.
https://twitter.com/taku910/status/655066284556554240

**Comment by stevengj** [comment]
He still seems to think it has something to do with Javascript (if Google is translating the conversation properly).  There is no single-codepoint ("composed") version of ｸﾞ, as you can see if you do NFC normalization of the string by `collect(normalize_string("ｸﾞ", :NFC))` — NFC creates composed characters where possible.  The only representation of ｸﾞ in Unicode is the decomposed (two-character) version.

If he doesn't know how to fix the model, does that mean that we shouldn't put it in UW3 either?  i.e. we should just remove it entirely?  If the score of ｸﾞis correct, then putting it in `UW3` makes sense.

**Comment by chezou** [comment]
In Japanese, we often normalize half-width Katakana to full-width Katakana, like from `ｸﾞ` to  `グ`, and he  might have normalized half-width Katakana to full-width (but nobody knows...).
And recently, we only use half-width Katakana in some special case, so it's not a big problem.

So, I think removing `ｸﾞ` is OK.

**Comment by stevengj** [comment]
Actually, I don't think you should remove it.  You already have the rule `'グ' => 1319`, which was handled correctly since グ is a single codepoint.   So, the same score should clearly be used for ｸﾞ.

**Pull request merged**
